import { StyleSheet } from 'react-native';
import { GlobalColors, GlobalFont, GlobalFontSizes } from './Styles';

const colorText = GlobalColors.TEXT_PRIMARY
const reguler = GlobalFont.Gotham.reguler
const medium = GlobalFont.Gotham.medium
const mediumItalic = GlobalFont.Gotham.mdItalic
const bold = GlobalFont.Gotham.bold

const textStyles = StyleSheet.create({
    //reguler
    text8: { fontSize: GlobalFontSizes[8], fontFamily: reguler, color: colorText },
    text9: { fontSize: GlobalFontSizes[9], fontFamily: reguler, color: colorText },
    text10: { fontSize: GlobalFontSizes[10], fontFamily: reguler, color: colorText },
    text11: { fontSize: GlobalFontSizes[11], fontFamily: reguler, color: colorText },
    text12: { fontSize: GlobalFontSizes[12], fontFamily: reguler, color: colorText },
    text13: { fontSize: GlobalFontSizes[13], fontFamily: reguler, color: colorText },
    text14: { fontSize: GlobalFontSizes[14], fontFamily: reguler, color: colorText },
    text15: { fontSize: GlobalFontSizes[15], fontFamily: reguler, color: colorText },
    text16: { fontSize: GlobalFontSizes[16], fontFamily: reguler, color: colorText },
    text17: { fontSize: GlobalFontSizes[17], fontFamily: reguler, color: colorText },
    text18: { fontSize: GlobalFontSizes[18], fontFamily: reguler, color: colorText },
    text19: { fontSize: GlobalFontSizes[19], fontFamily: reguler, color: colorText },
    text20: { fontSize: GlobalFontSizes[20], fontFamily: reguler, color: colorText },
    text21: { fontSize: GlobalFontSizes[21], fontFamily: reguler, color: colorText },
    text22: { fontSize: GlobalFontSizes[22], fontFamily: reguler, color: colorText },
    text23: { fontSize: GlobalFontSizes[23], fontFamily: reguler, color: colorText },
    text24: { fontSize: GlobalFontSizes[24], fontFamily: reguler, color: colorText },
    text25: { fontSize: GlobalFontSizes[25], fontFamily: reguler, color: colorText },
    text26: { fontSize: GlobalFontSizes[26], fontFamily: reguler, color: colorText },
    text27: { fontSize: GlobalFontSizes[27], fontFamily: reguler, color: colorText },
    text28: { fontSize: GlobalFontSizes[28], fontFamily: reguler, color: colorText },
    text29: { fontSize: GlobalFontSizes[29], fontFamily: reguler, color: colorText },
    text30: { fontSize: GlobalFontSizes[30], fontFamily: reguler, color: colorText },

    //Medium
    textMd8: { fontSize: GlobalFontSizes[8], fontFamily: medium, color: colorText },
    textMd9: { fontSize: GlobalFontSizes[9], fontFamily: medium, color: colorText },
    textMd10: { fontSize: GlobalFontSizes[10], fontFamily: medium, color: colorText },
    textMd11: { fontSize: GlobalFontSizes[11], fontFamily: medium, color: colorText },
    textMd12: { fontSize: GlobalFontSizes[12], fontFamily: medium, color: colorText },
    textMd13: { fontSize: GlobalFontSizes[13], fontFamily: medium, color: colorText },
    textMd14: { fontSize: GlobalFontSizes[14], fontFamily: medium, color: colorText },
    textMd15: { fontSize: GlobalFontSizes[15], fontFamily: medium, color: colorText },
    textMd16: { fontSize: GlobalFontSizes[16], fontFamily: medium, color: colorText },
    textMd17: { fontSize: GlobalFontSizes[17], fontFamily: medium, color: colorText },
    textMd18: { fontSize: GlobalFontSizes[18], fontFamily: medium, color: colorText },
    textMd19: { fontSize: GlobalFontSizes[19], fontFamily: medium, color: colorText },
    textMd20: { fontSize: GlobalFontSizes[20], fontFamily: medium, color: colorText },
    textMd21: { fontSize: GlobalFontSizes[21], fontFamily: medium, color: colorText },
    textMd22: { fontSize: GlobalFontSizes[22], fontFamily: medium, color: colorText },
    textMd23: { fontSize: GlobalFontSizes[23], fontFamily: medium, color: colorText },
    textMd24: { fontSize: GlobalFontSizes[24], fontFamily: medium, color: colorText },
    textMd25: { fontSize: GlobalFontSizes[25], fontFamily: medium, color: colorText },
    textMd26: { fontSize: GlobalFontSizes[26], fontFamily: medium, color: colorText },
    textMd27: { fontSize: GlobalFontSizes[27], fontFamily: medium, color: colorText },
    textMd28: { fontSize: GlobalFontSizes[28], fontFamily: medium, color: colorText },
    textMd29: { fontSize: GlobalFontSizes[29], fontFamily: medium, color: colorText },
    textMd30: { fontSize: GlobalFontSizes[30], fontFamily: medium, color: colorText },

    //Bold
    textBold8: { fontSize: GlobalFontSizes[8], fontFamily: bold, color: colorText },
    textBold9: { fontSize: GlobalFontSizes[9], fontFamily: bold, color: colorText },
    textBold10: { fontSize: GlobalFontSizes[10], fontFamily: bold, color: colorText },
    textBold11: { fontSize: GlobalFontSizes[11], fontFamily: bold, color: colorText },
    textBold12: { fontSize: GlobalFontSizes[12], fontFamily: bold, color: colorText },
    textBold13: { fontSize: GlobalFontSizes[13], fontFamily: bold, color: colorText },
    textBold14: { fontSize: GlobalFontSizes[14], fontFamily: bold, color: colorText },
    textBold15: { fontSize: GlobalFontSizes[15], fontFamily: bold, color: colorText },
    textBold16: { fontSize: GlobalFontSizes[16], fontFamily: bold, color: colorText },
    textBold17: { fontSize: GlobalFontSizes[17], fontFamily: bold, color: colorText },
    textBold18: { fontSize: GlobalFontSizes[18], fontFamily: bold, color: colorText },
    textBold19: { fontSize: GlobalFontSizes[19], fontFamily: bold, color: colorText },
    textBold20: { fontSize: GlobalFontSizes[20], fontFamily: bold, color: colorText },
    textBold21: { fontSize: GlobalFontSizes[21], fontFamily: bold, color: colorText },
    textBold22: { fontSize: GlobalFontSizes[22], fontFamily: bold, color: colorText },
    textBold23: { fontSize: GlobalFontSizes[23], fontFamily: bold, color: colorText },
    textBold24: { fontSize: GlobalFontSizes[24], fontFamily: bold, color: colorText },
    textBold25: { fontSize: GlobalFontSizes[25], fontFamily: bold, color: colorText },
    textBold26: { fontSize: GlobalFontSizes[26], fontFamily: bold, color: colorText },
    textBold27: { fontSize: GlobalFontSizes[27], fontFamily: bold, color: colorText },
    textBold28: { fontSize: GlobalFontSizes[28], fontFamily: bold, color: colorText },
    textBold29: { fontSize: GlobalFontSizes[29], fontFamily: bold, color: colorText },
    textBold30: { fontSize: GlobalFontSizes[30], fontFamily: bold, color: colorText },

    //Medium Italic
    textMdItalic8: { fontSize: GlobalFontSizes[8], fontFamily: mediumItalic, color: colorText },
    textMdItalic9: { fontSize: GlobalFontSizes[9], fontFamily: mediumItalic, color: colorText },
    textMdItalic10: { fontSize: GlobalFontSizes[10], fontFamily: mediumItalic, color: colorText },
    textMdItalic11: { fontSize: GlobalFontSizes[11], fontFamily: mediumItalic, color: colorText },
    textMdItalic12: { fontSize: GlobalFontSizes[12], fontFamily: mediumItalic, color: colorText },
    textMdItalic13: { fontSize: GlobalFontSizes[13], fontFamily: mediumItalic, color: colorText },
    textMdItalic14: { fontSize: GlobalFontSizes[14], fontFamily: mediumItalic, color: colorText },
    textMdItalic15: { fontSize: GlobalFontSizes[15], fontFamily: mediumItalic, color: colorText },
    textMdItalic16: { fontSize: GlobalFontSizes[16], fontFamily: mediumItalic, color: colorText },
    textMdItalic17: { fontSize: GlobalFontSizes[17], fontFamily: mediumItalic, color: colorText },
    textMdItalic18: { fontSize: GlobalFontSizes[18], fontFamily: mediumItalic, color: colorText },
    textMdItalic19: { fontSize: GlobalFontSizes[19], fontFamily: mediumItalic, color: colorText },
    textMdItalic20: { fontSize: GlobalFontSizes[20], fontFamily: mediumItalic, color: colorText },
    textMdItalic21: { fontSize: GlobalFontSizes[21], fontFamily: mediumItalic, color: colorText },
    textMdItalic22: { fontSize: GlobalFontSizes[22], fontFamily: mediumItalic, color: colorText },
    textMdItalic23: { fontSize: GlobalFontSizes[23], fontFamily: mediumItalic, color: colorText },
    textMdItalic24: { fontSize: GlobalFontSizes[24], fontFamily: mediumItalic, color: colorText },
    textMdItalic25: { fontSize: GlobalFontSizes[25], fontFamily: mediumItalic, color: colorText },
    textMdItalic26: { fontSize: GlobalFontSizes[26], fontFamily: mediumItalic, color: colorText },
    textMdItalic27: { fontSize: GlobalFontSizes[27], fontFamily: mediumItalic, color: colorText },
    textMdItalic28: { fontSize: GlobalFontSizes[28], fontFamily: mediumItalic, color: colorText },
    textMdItalic29: { fontSize: GlobalFontSizes[29], fontFamily: mediumItalic, color: colorText },
    textMdItalic30: { fontSize: GlobalFontSizes[30], fontFamily: mediumItalic, color: colorText },
})

export default textStyles;